---
- name: Install Kubenetes Rancher hosts
  hosts: tag_Name_kubernetes_host
  tasks:
    - name: Intall docker
      shell: curl https://releases.rancher.com/install-docker/1.12.sh | sh
      become: true
      become_method: sudo
  tags:
    - rancher-host
