---
- name: test
  hosts: localhost
  roles:
    - {
        role: rancher-kubernetes,
        project_name: kubernetes,
        rancher_server: rancherelb-666093380.us-east-2.elb.amazonaws.com,
        rancher_port: 8080
      }
