# Check pre-requisites
- include: pre-requisites.yml

# Create Security groups
- name: "AWS | Provision Security Groups | Create Security Groups"
  ec2_group:
    name: "{{ item.name }}"
    description: "{{ item.desc }}"
    rules: "{{ item.rules }}"
    rules_egress: "{{ item.rules_egress }}"
    region: "{{ vpc_region }}"
    state: "{{ ec2_group_state }}"
    ec2_access_key: "{{ access_key }}"
    ec2_secret_key: "{{ secret_key }}"
  with_items: "{{ ec2_sg }}"
  register: ec2_sg_reg

- debug: var=ec2_sg_reg verbosity=4

- name: "AWS | Provision Security Groups | Tag Security Groups"
  ec2_tag:
      resource: "{{ item.group_id}}"
      region: "{{ vpc_region }}"
      state: "present"
      tags: "{{ security_group_resource_tags }}"
  with_items: "{{ ec2_sg_reg.results }}"

  when: ec2_group_state == "present"
