---
# install the latest version of docker
- include: current-docker.yml
  when: docker_version == "latest"

# install an older version of docker
- include: old-docker.yml
  when: docker_version != "latest"
