---
# install docker host on all linux hosts

- name: Docker | Install Docker | Install prerequisites
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  become: true
  become_method: sudo
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Docker | Install Docker | Add Docker’s official GPG key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: "hkp://ha.pool.sks-keyservers.net:80"
    state: present
  become: true
  become_method: sudo

- name: Docker | Install Docker | Add Docker repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    state: present
  become: true
  become_method: sudo

- name: Docker | Install Docker | Install Docker host
  apt:
    name: docker-engine=1.12.6-0~ubuntu-xenial
    update_cache: yes
    state: present
  become: true
  become_method: sudo


- name: Docker | Install Docker | Create Docker group
  group:
    name: docker
    state: present

- name: Docker | Install Docker | Add Docker group to local user
  user:
    name: ubuntu
    comment: "add user to docker group"
    groups: docker
    append: yes
  become: true
  become_method: sudo

- name: Docker | Install Docker | Enable Docker service at boot
  systemd:
    name: docker
    enabled: yes
  become: true
  become_method: sudo
